// project list — only these 5
const projects = [
  {
    name: 'Jitter',
    url:  'https://github.com/SanoBld/Jitter',
    repo: 'SanoBld/Jitter',
    category: 'app',
    desc: { fr: 'Test de vitesse internet', en: 'Internet speed test' },
  },
  {
    name: 'LastStats',
    url:  'https://sanobld.github.io/LastStats/',
    repo: 'SanoBld/LastStats-App',
    category: 'music',
    desc: { fr: 'Last.fm en plus beau', en: 'Last.fm, beautifully redesigned' },
  },
  {
    name: 'LastStats App',
    url:  'https://github.com/SanoBld/LastStats-App/releases/latest',
    repo: 'SanoBld/LastStats-App',
    category: 'app',
    desc: { fr: 'Version app Android & Windows', en: 'Android & Windows native app' },
  },
  {
    name: "SO'BÔHÈME",
    url:  'https://soboheme.github.io/Web/',
    repo: 'SoBoheme/Web',
    category: 'web',
    desc: { fr: 'Vitrine de boutique en ligne', en: 'Online boutique showcase' },
  },
  {
    name: 'Metrolist',
    url:  'https://metrolist.cc/',
    repo: 'MetrolistGroup/Metrolist',
    category: 'web',
    desc: { fr: 'Client YouTube Music moderne', en: 'Modern YouTube Music client' },
  },
];

// category labels in both languages
const CAT_LABELS = {
  music: { fr: 'Musique', en: 'Music' },
  web:   { fr: 'Web',     en: 'Web'   },
  app:   { fr: 'App',     en: 'App'   },
};

// all UI text in french and english
const i18n = {
  fr: {
    heroSub:        'Développeur & Designer',
    sectionTag:     'Travaux Choisis',
    sectionTitle:   'Projets',
    aboutTag:       'Identité',
    aboutTitle:     'À propos',
    aboutText:      'Développeur & designer quelque part en France. Interfaces Last.fm soignées, client YouTube Music, apps Android & Windows — du code propre sur toutes les plateformes.',
    ctaTitle:       "Voir l'ensemble du travail",
    ctaBtn:         'Voir sur GitHub',
    footer:         '© 2025 Sano Bld',
    navProjects:    'Projets',
    navAbout:       'À propos',
    navGithub:      'GitHub',
    filterAll:      'Tout',
    filterMusic:    'Musique',
    filterWeb:      'Web',
    filterApp:      'App',
    cursorOpen:     'VOIR',
    cmdPlaceholder: 'Taper une commande…',
    cmdGoProjects:  'Aller aux Projets',
    cmdGoAbout:     'Aller à À propos',
    cmdTheme:       'Changer le thème',
    cmdLang:        'Changer la langue',
    cmdGithub:      'Ouvrir GitHub',
    cmdEmpty:       'Aucun résultat',
    toastTheme:     'Thème changé',
    toastGithub:    'Ouverture GitHub…',
    konamiMsg:      '👑 Mode Royal — Activé',
    shortcutsHint:  'D = Thème · G = GitHub · K = Palette',
    themeLight:     'Clair',
    themeDark:      'Sombre',
    themeAuto:      'Auto',
    commitLoading:  'chargement…',
    stars:          'étoiles',
  },
  en: {
    heroSub:        'Developer & Designer',
    sectionTag:     'Selected Work',
    sectionTitle:   'Projects',
    aboutTag:       'Identity',
    aboutTitle:     'About',
    aboutText:      'Developer & designer somewhere in France. Last.fm interfaces, YouTube Music client, Android & Windows apps — clean code shipped on every platform.',
    ctaTitle:       'See the full picture',
    ctaBtn:         'View on GitHub',
    footer:         '© 2025 Sano Bld',
    navProjects:    'Projects',
    navAbout:       'About',
    navGithub:      'GitHub',
    filterAll:      'All',
    filterMusic:    'Music',
    filterWeb:      'Web',
    filterApp:      'App',
    cursorOpen:     'OPEN',
    cmdPlaceholder: 'Type a command…',
    cmdGoProjects:  'Go to Projects',
    cmdGoAbout:     'Go to About',
    cmdTheme:       'Toggle theme',
    cmdLang:        'Toggle language',
    cmdGithub:      'Open GitHub',
    cmdEmpty:       'No results',
    toastTheme:     'Theme toggled',
    toastGithub:    'Opening GitHub…',
    konamiMsg:      '👑 Royal Mode — Activated',
    shortcutsHint:  'D = Theme · G = GitHub · K = Palette',
    themeLight:     'Light',
    themeDark:      'Dark',
    themeAuto:      'Auto',
    commitLoading:  'loading…',
    stars:          'stars',
  },
};
